# your domain
domain: momozi.tk

# database url
database_url: ""

# cloudflare api
cf_email: ""
cf_key: ""

# source definition file
source-files:
  - https://cdn.jsdelivr.net/gh/guobang-yoo/CDN@master/tmp/proxypool/source.yaml